export enum SpellCategory {
    CHARM = 'charm',
    SPELL = 'spell',
    HEALING_SPELL = 'healing spell',
    VANISHMENT = 'vanishment',
    TRANSFIGURATION = 'transfiguration',
    DARK_CHARM = 'dark charm',
    JINX = 'jinx',
    CURSE = 'curse',
    MAGICAL_TRANSPORTATION = 'magical transportation',
    CONJURATION = 'conjuration',
    HEX = 'hex',
    TRANSFORMATION = 'transformation',
    COUNTER_CHARM = 'counter-charm',
    COUNTER_SPELL = 'counter-spell',
    DARK_ARTS = 'dark arts',
    COUNTER_CURSE = 'counter-curse',
    COUNTER_JINX = 'counter-jinx',
    BINDING_MAGICAL_CONTRACT = 'binding magical contract',
  }